apiVersion: v1
kind: Service
metadata:
  name: rollout-canary
  labels:
    app: rollout-canary
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: rollout-canary
  type: NodePort
