apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-canary-example
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-canary
  template:
    metadata:
      labels:
        app: rollout-canary
    spec:
      containers:
      - name: rollouts-demo
        image: zxd46/example-apps:1.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "500Mi"
            cpu: "1"
          limits:
            memory: "1Gi"
        readinessProbe:
          httpGet:
            path: /products
            port: 8080
          periodSeconds: 5
          failureThreshold: 5
  strategy:
    canary:
      steps:
      - setWeight: 10
      - pause: {duration: 20s}
      - setWeight: 60
      - pause: {duration: 40s}
  progressDeadlineSeconds: 15
  progressDeadlineAbort: true